apiVersion: v1
kind: Service
metadata:
  name: svc-production-orlando-city
  namespace: orlando-city
spec:
  ports:
  - nodePort: 32333
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    app: production-orlando-city
