apiVersion: v1
kind: Pod
metadata:
  labels:
    app: busy
  name: busy
spec:
  containers:
  - name: busy
    image: busybox
    imagePullPolicy: Always
    command:
      - sleep
      - "3600"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    resources:
      limits:
        cpu: "1000m"
        memory: "1Gi"
      requests:
        cpu: "200m"
        memory: "512Mi"
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /vinicius
      name: vinicius-dir
  volumes:
  - name: vinicius-dir
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  schedulerName: default-scheduler
  terminationGracePeriodSeconds: 30
  nodeSelector:
    dc: US
