apiVersion: v1
kind: PersistentVolume
metadata:
  name: meu-segundo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/prometheus
    server: 10.1.203.235
    readOnly: false 
