apiVersion: v1
kind: PersistentVolume
metadata:
  name: meu-terceiro-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/alertmanager
    server: 10.1.203.235
    readOnly: false
 
