apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: nginx
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
      name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Always
        terminationMessagePath: /dev/termintaion-log
        terminationMessagePolicy: File
        ports:
        - containerPort: 80
          protocol: TCP  
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "150m"
            memory: "128Mi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30       
     
