apiVersion: v1
kind: Service
metadata:
  name: svc-desenvolvimento-orlando-city
  namespace: orlando-city
spec:
  ports:
  - nodePort: 32666
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    app: desenvolvimento-orlando-city
