apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx
  namespace: nginx-app
spec:
  resources:
    limits:
      storage: "2Gi"
    requests:
      storage: "2Gi"
  accessModes:
  - ReadWriteMany
