apiVersion: apps/v1
kind: Deployment
metadata:
  name: meuprimeirodeployment
spec:
  replicas: 20
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: kubedevio/nginx-color:green
