apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-repo-linux
  namespace: repo-linux
spec:
  capacity:
    storage: "20Gi"
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/repo-linux
    server: 10.1.203.235
    readOnly: false
  
