apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-linux
  labels:
    app: repo-linux
  namespace: repo-linux
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: repo-linux
  template:
    metadata:
      labels:
        app: repo-linux
    spec:
      containers:
      - name: repo-linux
        image: viniciusalcantara2018/repo-linux-images:1.0
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          limits:
            cpu: "150m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "150Mi"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-dir-html
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: install
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - > 
          echo '<html><head><title>Download ISOs Linux</title></head><body><h3>Download Latest Images - Linux </h3><ul><li><a href="CentOS-8.3.2011-x86_64-dvd1.iso" download>Centos 8.3</a></li><li><a href="debian-10.8.0-amd64-DVD-2.iso" download>Debian 10</a></li><li><a href="ubuntu-20.04.2-live-server-amd64.iso" download>Ubuntu Server 20.04.2</a></li></ul></body></html>' > /work-dir/index.html
        volumeMounts:
        - name: nginx-dir-html
          mountPath: "/work-dir"
      volumes:
      - name: nginx-dir-html
        persistentVolumeClaim:
          claimName: pvc-repo-linux
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 60
      nodeSelector:
        environment: ENV-PRODUCAO


 
