apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  namespace: default
spec:
  selector:
    app: nginx
  sessionAffinity: ClientIP
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 80
  type: ClusterIP
    
