apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx
  namespace: nginx-app
spec:
  capacity:
    storage: "2Gi"
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/nginx-app
    server: 10.1.203.235
    readOnly: false
