apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx
  namespace: nginx-app
spec:
  accessModes:
  - ReadWriteMany
  resources:
    limits:
      storage: "2Gi"
    requests:
      storage: "2Gi"


