apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  namespace: nginx-app
spec:
  selector:
    app: nginx
  ports:
  - nodePort: 32222
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
