apiVersion: v1
kind: Service
metadata:
  name: svc-staging-repo-linux
  namespace: repo-linux
spec:
  ports:
  - nodePort: 32101
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    app: staging-repo-linux
