apiVersion: apps/v1
kind: Deployment
metadata:
  name: develop-curriculo-generator
  labels:
    app: develop-curriculo-generator
  namespace: curriculo-generator
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: develop-curriculo-generator
  template:
    metadata:
      labels:
        app: develop-curriculo-generator
    spec:
      containers:
      - name: develop-curriculo-generator
        image: viniciusalcantara2018/curriculo-dev:1.0
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          limits:
            cpu: "400m"
            memory: "800Mi"
          requests:
            cpu: "300m"
            memory: "512Mi"
        ports:
        - containerPort: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 60
      nodeSelector:
        environment: ENV-DESENVOLVIMENTO


 
