apiVersion: v1
kind: Service
metadata:
  name: svc-curriculo-generator
  namespace: curriculo-generator
spec:
  ports:
  - nodePort: 32777
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    app: curriculo-generator
