apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  namespace: repo-linux
spec:
  ports:
  - nodePort: 32222
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    app: repo-linux
