apiVersion: v1
kind: Service
metadata:
  name: svc-develop-repo-linux
  namespace: repo-linux
spec:
  ports:
  - nodePort: 32555
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    app: develop-repo-linux
