apiVersion: v1
kind: Service
metadata:
  name: svc-staging-curriculo-generator
  namespace: curriculo-generator
spec:
  ports:
  - nodePort: 32103
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    app: staging-curriculo-generator
